# Generated by Django 5.0.4 on 2024-04-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_emp',
        ),
    ]
